version: '3'
services:
  test:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_FILE=target/*.jar
    ports:
      - "8086:8086"
    restart: always